name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code (with submodules if applicable)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Set up Go (for gomobile)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Adjust to the Go version required by your project

      # Step 3: Install gomobile
      - name: Install gomobile
        run: go install golang.org/x/mobile/cmd/gomobile@latest

      # Step 4: Initialize gomobile
      - name: Initialize gomobile
        run: gomobile init

      # Step 5: Build libbox with gomobile
      - name: Build libbox with gomobile
        run: |
          cd go-libbox # Adjust the path to your Go module
          gomobile bind -o ../app/libs/libbox.aar -target=android

      # Step 6: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 7: Set up Android SDK and NDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '28.0.13004108'

      # Step 8: Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 9: Build the app with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 10: (Optional) Run tests
      - name: Run tests
        run: ./gradlew test

      # Step 11: (Optional) Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: app/build/outputs/apk/debug/app-debug.apk